version: '3.7'

services:
  etcd-node1:
    image: quay.io/coreos/etcd:v3.4.15
    volumes:
      - etcd-data-node1:/etcd-data
    command: >
      /usr/local/bin/etcd
      --name node1
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd-node1:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd-node1:2380
      --initial-cluster node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
      --initial-cluster-token etcd-cluster-1
      --initial-cluster-state new
    networks:
      - etcd-net
    ports:
      - "12379:2379"
      - "12380:2380"

  etcd-node2:
    image: quay.io/coreos/etcd:v3.4.15
    volumes:
      - etcd-data-node2:/etcd-data
    command: >
      /usr/local/bin/etcd
      --name node2
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd-node2:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd-node2:2380
      --initial-cluster node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
      --initial-cluster-token etcd-cluster-1
      --initial-cluster-state new
    networks:
      - etcd-net
    ports:
      - "22379:2379"
      - "22380:2380"

  etcd-node3:
    image: quay.io/coreos/etcd:v3.4.15
    volumes:
      - etcd-data-node3:/etcd-data
    command: >
      /usr/local/bin/etcd
      --name node3
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd-node3:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd-node3:2380
      --initial-cluster node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
      --initial-cluster-token etcd-cluster-1
      --initial-cluster-state new
    networks:
      - etcd-net
    ports:
      - "32379:2379"
      - "32380:2380"

networks:
  etcd-net:
    driver: bridge

volumes:
  etcd-data-node1:
    driver: local
  etcd-data-node2:
    driver: local
  etcd-data-node3:
    driver: local
